# Generated by Django 2.2 on 2019-12-25 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='title',
            field=models.CharField(default='default channel', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gender',
            name='gender',
            field=models.CharField(default='other', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='file',
            field=models.URLField(default='', verbose_name='static/avi/mock_file.jpg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='status',
            field=models.CharField(default='user', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='youtube.Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default='', max_length=32, unique=True, verbose_name='User name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.ForeignKey(default='other', on_delete=django.db.models.deletion.CASCADE, to='youtube.Status'),
            preserve_default=False,
        ),
    ]
