# Generated by Django 2.2 on 2019-12-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_auto_20191225_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
