# Generated by Django 2.2 on 2019-12-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0009_auto_20191225_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='youtube/static/youtube/media/media/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screen_shot',
            field=models.ImageField(blank=True, null=True, upload_to='youtube/static/youtube/media/'),
        ),
    ]
