# Generated by Django 2.2 on 2019-12-26 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0011_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExpressionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='youtube/static/youtube/media/'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='expression',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.Movie'),
        ),
        migrations.AddField(
            model_name='expression',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube.ExpressionType'),
        ),
        migrations.AddField(
            model_name='expression',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.User'),
        ),
        migrations.AlterUniqueTogether(
            name='expression',
            unique_together={('movie', 'user')},
        ),
    ]
