# Generated by Django 2.2 on 2019-12-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0012_auto_20191226_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.FileField(upload_to='youtube/static/youtube/media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='file',
        ),
        migrations.CreateModel(
            name='Miniature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.FileField(upload_to='youtube/static/youtube/media/')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.File')),
            ],
        ),
    ]
