# Generated by Django 2.2 on 2019-12-26 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0013_auto_20191226_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='movie',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='youtube.Movie'),
            preserve_default=False,
        ),
    ]
